# Basic settings
task: "MIS"
mode: "train"
train_data_size: 64000
val_data_size: 500
sparse_factor: 1
store_data: False

# Dataset paths
data:
  train_path: '../data/ml4co_mis/train_dataset/mis/mis_rb_large'
  val_path: '../data/ml4co_mis/val_dataset/mis/mis_rb-large_val.txt' # Using the same for validation example
  test_path: '../data/ml4co_mis/test_dataset/mis/mis_rb-large_kamis-60s_43.004.txt' # Using the same for validation example

# Training parameters
train:
  batch_size: 1
  num_workers: 2
  learning_rate: 0.0002
  ckpt_dir: "./runs/rblarge_prefix_model"
  resume_ckpt:  # optional: checkpoint to initialize from
  devices: [0, 1] # <-- ADD THIS! Specify the GPU IDs you want to use.

  # Curriculum stages
  curriculum:
    stage1:
      name: "stage1_large_prefix"
      epochs: 30
      prefix_k_options: [0, 0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18,0.19, 0.2,0.21,0.22,0.23,0.24,0.25,0.26,0.27,0.28,0.29, 0.3,0.35, 0.4,0.45, 0.5]
    stage2:
      name: "stage2_medium_prefix"
      epochs: 30
      prefix_k_options: [0,0.1, 0.2, 0.3, 0.4, 0.5]
    stage3:
      name: "stage3_small_prefix"
      epochs: 30
      prefix_k_options: [0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18,0.19, 0.2,0.21,0.22,0.23,0.24,0.25,0.26,0.27,0.28,0.29, 0.3,0.31,0.32,0.33,0.34,0.35,0.36,0.37,0.38,0.39, 0.4,0.45, 0.5]
# Validation parameters
val:
  batch_size: 12

# Encoder config
encoder:
  task: "MIS"
  sparse: True
  block_layers: [2, 4, 4, 2]
  hidden_dim: 256
  prefix_cond_dim: 256
  prefix_enc_hidden_dim: 256
  time_flag: True # make sure the time embedding is enabled

# Decoder config
decoder:
  decode_kwargs:
    use_rlsa: False

# Core CM model parameters
model_params:
  cm_alpha: 0.2
  cm_beta: 0.025
  prompt_prob: 0.1
  delta_scale: [0.0, 1.0]
  inference_steps: 1
  determinate_steps: 4
  beam_size: -1
  energy_finetune: False
